- CHANGELOG.md
- README.md
- lua/haskell-tools/config.lua
- lua/haskell-tools/deps.lua
- lua/haskell-tools/lsp.lua
> Basic codeLens support

- CHANGELOG.md
- README.md
- lua/haskell-tools/config.lua
- lua/haskell-tools/deps.lua
- lua/haskell-tools/hoogle-local.lua
- lua/haskell-tools/hoogle-web.lua
- lua/haskell-tools/hoogle.lua
- lua/haskell-tools/init.lua
- lua/haskell-tools/lsp.lua
- lua/haskell-tools/telescope-util.lua
- lua/haskell-tools/util.lua
> hoogle search

- CHANGELOG.md
- README.md
- lua/haskell-tools/telescope-util.lua
> feat(hoogle): enable filling holes using telescope hoogle search

- CHANGELOG.md
- README.md
- lua/haskell-tools/repl.lua
> feat(repl): load files and paste multiple lines

- CHANGELOG.md
- lua/haskell-tools/hoogle/util.lua
> fix(hoogle): broken <c-b> keymap

- CHANGELOG.md
- README.md
- lua/haskell-tools/project-util.lua
- lua/haskell-tools/project.lua
- lua/telescope/_extensions/ht.lua
- lua/telescope/_extensions/ht/extension.lua
> feat(telescope): package grep & file search + register extension

- .github/workflows/pr.yml
> ci: add conventional-pr-action

- .github/workflows/pr.yml
- CHANGELOG.md
- README.md
- lua/haskell-tools/config.lua
- lua/haskell-tools/hoogle.lua
- lua/haskell-tools/hoogle/local.lua
- lua/haskell-tools/hoogle/util.lua
- lua/haskell-tools/hoogle/web.lua
- lua/haskell-tools/lsp.lua
- lua/haskell-tools/lsp/hover.lua
- lua/haskell-tools/util.lua
> feat: hover actions

- README.md
> docs(readme): remove asciicast titles

- CHANGELOG.md
> docs(changelog): prepare 1.3.0 release notes

- CHANGELOG.md
- README.md
- lua/haskell-tools/config.lua
- lua/haskell-tools/lsp.lua
- lua/haskell-tools/lsp/definition.lua
- lua/haskell-tools/lsp/hover.lua
- lua/haskell-tools/util.lua
> Hover hoogle extend

- CHANGELOG.md
- lua/haskell-tools/lsp/hover.lua
>  fix(hover): smarter go-to-definition detection 

- CHANGELOG.md
- lua/haskell-tools/hoogle/util.lua
...in type signature
fixes #57
> fix(hoogle): replace duplicate whitespace with single whitespace

- CHANGELOG.md
- README.md
- lua/haskell-tools/config.lua
- lua/haskell-tools/hoogle.lua
- lua/haskell-tools/init.lua
- lua/haskell-tools/lsp.lua
- lua/haskell-tools/lsp/definition.lua
- lua/haskell-tools/project-util.lua
- lua/haskell-tools/tags.lua
> feat(tags) + fix(codeLens auto-refresh)

- CHANGELOG.md
- lua/haskell-tools/config.lua
> fix(hls): missing settings table in config

- flake.lock
- flake.nix
- nix/test-overlay.nix
> tests: add neovim-nightly tests

- default.nix
- flake.nix
- nix/haskell-tooling-overlay.nix
- nix/test-overlay.nix
- shell.nix
> style: replace nixpkgs-fmt with alejandra

- CHANGELOG.md
- lua/haskell-tools/config.lua
> feat: add cabal & cabalproject lsp filetypes

- CHANGELOG.md
- README.md
- lua/haskell-tools/log.lua
> feat: ability to set the log level for the current session

- CHANGELOG.md
- lua/haskell-tools/repl.lua
- lua/haskell-tools/util.lua
> fix(repl): quote file names

- CHANGELOG.md
- README.md
- flake.lock
- flake.nix
- lua/haskell-tools/config.lua
- lua/haskell-tools/repl.lua
- lua/haskell-tools/repl/builtin.lua
- lua/haskell-tools/repl/toggleterm.lua
- nix/test-overlay.nix
- tests/repl_spec.lua
> feat: add auto_focus option to repl

- doc/haskell-tools.txt
- lua/haskell-tools/hoogle.lua
- lua/haskell-tools/repl.lua
> chore: do not expose internal handlers

- README.md
> docs(readme): remove unavailable scout project from recommendations

- .luacheckrc
- .luarc.json
- CONTRIBUTING.md
- doc/haskell-tools.txt
- flake.nix
- lua/haskell-tools/config.lua
- lua/haskell-tools/hoogle.lua
- lua/haskell-tools/repl.lua
- lua/haskell-tools/repl/builtin.lua
- nix/test-overlay.nix
> ci: add linting

- CHANGELOG.md
- lua/haskell-tools/hoogle.lua
- lua/haskell-tools/hoogle/local.lua
- lua/haskell-tools/hoogle/web.lua
- lua/haskell-tools/util.lua
- tests/hoogle_spec.lua
- [ x] Tested, as applicable:
- [x ] Added plenary specs
- [x ] Updated [CHANGELOG.md](https://github.com/MrcJkb/haskell-tools.nvim/blob/master/CHANGELOG.md) (if applicable).
- [x ] Fits [CONTRIBUTING.md](https://github.com/MrcJkb/haskell-tools.nvim/blob/master/CONTRIBUTING.md)
> fix(hoogle): fall back to browser if telescope is not set up

- CHANGELOG.md
- README.md
- doc/haskell-tools.txt
- lua/haskell-tools/config.lua
- lua/haskell-tools/config/check.lua
- lua/haskell-tools/health.lua
> feat: add health checks + config validation

- CHANGELOG.md
- lua/haskell-tools/lsp/hover.lua
> feat: add hover action for `textDocument/typeDefinition`

- .github/workflows/release.yml
- CHANGELOG.md
- README.md
- haskell-tools.nvim-scm-1.rockspec
Created a new PR because #83 got closed and cannot be reopened. For some reason GitHub thinks it has over 250 commits.
> feat: add rockspec

- README.md
- flake.lock
- flake.nix
- lua/haskell-tools/deps.lua
- nix/test-overlay.nix
- tests/repl_spec.lua
> tests: add test with nixpkgs.wrapNeovim

- CHANGELOG.md
- README.md
- doc/haskell-tools.txt
- lua/haskell-tools/lsp.lua
- lua/haskell-tools/lsp/eval.lua
- lua/haskell-tools/lsp/util.lua
> feat(lsp): evaluate all code snippets in comments at once

- CHANGELOG.md
- README.md
- doc/haskell-tools.txt
- flake.lock
- lua/haskell-tools/config.lua
- lua/haskell-tools/config/check.lua
- lua/haskell-tools/init.lua
- lua/haskell-tools/lsp.lua
- lua/haskell-tools/tags.lua
- lua/telescope/_extensions/ht/extension.lua
> feat: add support for ftplugin/haskell.lua

- lua/haskell-tools/health.lua
> fix: typo :)

- CHANGELOG.md
- flake.nix
- lua/haskell-tools/init.lua
- lua/haskell-tools/lsp.lua
- nix/test-overlay.nix
- tests/lsp_spec.lua
> fix(lsp): silent failure if hls executable not found

- CHANGELOG.md
- lua/haskell-tools/project-util.lua
- lua/haskell-tools/project.lua
- lua/haskell-tools/repl.lua
* This also changes `HsProjectFile` to fall back to *.cabal files
Fixes #146
> fix(repl): detection of single-package cabal projects

- CHANGELOG.md
- lua/haskell-tools/hoogle.lua
- lua/haskell-tools/hoogle/web.lua
- nix/test-overlay.nix
- tests/hoogle_spec.lua
> fix(hoogle.web): url escaping

- CHANGELOG.md
- README.md
- doc/haskell-tools.txt
- lua/haskell-tools/config.lua
- lua/haskell-tools/config/check.lua
- lua/haskell-tools/repl.lua
- nix/test-overlay.nix
- tests/fixtures/stack/single-package/simple.cabal
- tests/repl_spec.lua
> fix(repl): prefer stack if installed and stack files exist

- CHANGELOG.md
- lua/haskell-tools/lsp.lua
- lua/haskell-tools/lsp/util.lua
> fix(cabal): prevent error messages caused by external lsp plugins

- CHANGELOG.md
- lua/haskell-tools/lsp/util.lua
> fix(lsp): correct typo that broke codelens auto-refresh and stop/restart

- CHANGELOG.md
- lua/haskell-tools/lsp/hover.lua
> fix(hover): decode url-encoded (type-)definition paths in hover actions

- CHANGELOG.md
- README.md
- doc/haskell-tools.txt
- ftplugin/cabal.lua
- ftplugin/cabalproject.lua
- ftplugin/haskell.lua
- ftplugin/lhaskell.lua
- lua/haskell-tools/config.lua
- lua/haskell-tools/config/check.lua
- lua/haskell-tools/config/internal.lua
- lua/haskell-tools/dap.lua
- lua/haskell-tools/internal.lua
> feat: auto-discover dap configurations if conditions are met

- CHANGELOG.md
- lua/haskell-tools/hoogle/helpers.lua
> fix(hoogle): don't switch to insert mode on replace

- CHANGELOG.md
- README.md
- lua/haskell-tools/config/internal.lua
- lua/haskell-tools/log/init.lua
- lua/haskell-tools/log/internal.lua
> feat: logging improvements and fixes

- doc/haskell-tools.txt
- lua/haskell-tools/config/check.lua
- lua/haskell-tools/config/init.lua
- lua/haskell-tools/config/internal.lua
- lua/haskell-tools/hoogle/helpers.lua
- lua/haskell-tools/hoogle/web.lua
- lua/haskell-tools/lsp/hover.lua
Implement functionality discussed in #402.
> feat: add `open_url` config option

- lua/haskell-tools/repl/builtin.lua
> fix(repl/builtin): regression introduced in v4.4.1

- lua/telescope/_extensions/ht/extension.lua
> fix(telescope): `package_hsfiles` extension
